export default {
  FETCH_LIVE_EVENTS: 'FETCH_LIVE_EVENTS',
  RECEIVED_LIVE_EVENTS: 'RECEIVED_LIVE_EVENTS',

  FETCH_EVENT: 'FETCH_EVENT',
  RECEIVED_EVENT: 'RECEIVED_EVENT',

  FETCH_MARKET: 'FETCH_MARKET',
  RECIEVED_MARKET: 'RECIEVED_MARKET',

  TOGGLE_PRICES: 'TOGGLE_PRICES',

  OPENED_EVENT: 'OPENED_EVENT',
  CLOSED_EVENT: 'CLOSED_EVENT',
  ERROR: 'ERROR'
}